apiVersion: abtesting.com/v1
kind: ABTest
metadata:
  labels:
    app.kubernetes.io/name: ab-testing-operator
    app.kubernetes.io/managed-by: kustomize
  name: demo-service-abtest
spec:
  targetService: demo-service
  trafficWeight: 10
  image: nginx:latest
  port: 80
  replicas: 1
